### ISSUE TITLE
[Feature] Compatibility with Bronze Mod by JUNE

### ISSUE THREAD

**Issue by makumaku1974** [BlueStaggo/divergent-progression#1]
Bronze feature with this mod should be under iron, since bronze is tough but it's durability is weak.

**Comment by BlueStaggo** [comment]
It already has a mod that makes it compatible with Slow Your Roll so why not?

**Comment by BlueStaggo** [comment]
To be added in 1.1.0

**Comment by makumaku1974** [comment]
> It already has a mod that makes it compatible with Slow Your Roll so why not?

I have tried that mod but it's way too easy, slow bronze doesn't even make it a bit harder.
