### ISSUE TITLE
[BUG] Broken Items should be unusable 1.21

### ISSUE THREAD

**Issue by makumaku1974** [BlueStaggo/divergent-progression#2]
It can still break logs and mine stone even broken.
![image](https://github.com/user-attachments/assets/8fe25de8-25ef-444d-9f0f-1f8de773271c)

ps. Only axe is able to mine wood even broken.

**Comment by BlueStaggo** [comment]
Must be a compatibility issue because with this mod as the only mod this doesn't happen. Check for any mods that mixin into the ItemStack class or try disabling them one by one to see what's doing it.

**Comment by BlueStaggo** [comment]
I just pushed an update that has different mixins for controlling components. Can you try that version out and see if the bug is fixed for you?

**Comment by makumaku1974** [comment]
i will
