### ISSUE TITLE
[FEATURE] Advancements

### ISSUE THREAD

**Issue by makumaku1974** [BlueStaggo/divergent-progression#3]
Advancements that would affect the progress in crafting Flint Tools and Copper Tools for now.

**Comment by BlueStaggo** [comment]
A few vanilla advancements have already been adjusted to the new progression so I see no point in this, except for the fact that I probanly should change the Stone Age requirement to have copper instead of stone so I'll change that at some point.

**Comment by BlueStaggo** [comment]
What was I thinking? The stone age advancement is just fine since you need stone to smelt copper :P

**Comment by BlueStaggo** [comment]
What was I thinking? The stone age advancement is just fine since you need stone to smelt copper :P
