### ISSUE TITLE
Broken Tools causes "Error sending packet clientbound/minecraft:container_set_content" crash

### ISSUE THREAD

**Issue by FaeWulf** [BlueStaggo/divergent-progression#5]
As the title described, broken tools has an issue with Enchantment Component, it returns null (Which causes the #4) 

Reference from the library's author:
After checking the code, its' a bug in divergent-progression in the https://github.com/BlueStaggo/divergent-progression/blob/main/src/main/java/io/bluestaggo/divergeprog/mixin/ComponentHolderMixin.java. The issue is that it hardcodes enchantment prevention in get, but doesn't mirror the code in the constains, so it can return contains true, but get would still be null

I hope this can help?

**Comment by BlueStaggo** [comment]
Ohhh yeah that's quite the oversight. I'll fix it soon.
