### ISSUE TITLE
Datapack Recipe for other mods on list. 

### ISSUE THREAD

**Issue by makumaku1974** [BlueStaggo/divergent-progression#6]
Is there a certain tutorial for datapacks to change the recipe with modded items? I wanted to change alot of the modded items with your mod using datapacks. But I dont really have a damn clue on how to compile that. 

Simple as this by just removing diamonds and changing it into diamond bars.
![image](https://github.com/user-attachments/assets/5c1427ba-adbd-46fd-a8c3-ccb20504eff9)

**Comment by BlueStaggo** [comment]
This may help you: https://minecraft.wiki/w/Recipe
